name: Build EXE
icon: package
color: blue

description: 'Build EXE from python script with Nuitka'

inputs:
  output-dir:
    required: false
    type: string
    description: 'Directory for output builds'
    default: build
  script-name:
    required: true
    type: string
    description: 'name or path to python script'


runs:
  using: "composite"
  steps:

      - name: Install Dependencies
        shell: powershell
        run: |
          $github_action_path = "${{ github.action_path }}"
          # Fixes: C:\actions-runner\_work\repo\repo\./.github/actions/action-name
          $github_action_path = $github_action_path -replace "\\\./", "\"
          $github_action_path = $github_action_path -replace "/", "\"
          pip install -r "$github_action_path\requirements.txt"

      - name: Build EXE
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          python -m nuitka `
          --assume-yes-for-downloads `
          --standalone `
          --onefile `
          --output-dir="${{ inputs.output-dir }}" `
          ${{ inputs.script-name }}
